/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardWhatsappBotRouteImport } from './routes/dashboard/whatsapp-bot'
import { Route as DashboardUserManagementRouteImport } from './routes/dashboard/user-management'
import { Route as DashboardChatRouteImport } from './routes/dashboard/chat'
import { Route as DashboardAiAgentRouteImport } from './routes/dashboard/ai-agent'
import { Route as DashboardKnowledgeSourcesIndexRouteImport } from './routes/dashboard/knowledge-sources/index'
import { Route as DashboardKnowledgeSourcesFolderIdRouteImport } from './routes/dashboard/knowledge-sources/$folderId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardWhatsappBotRoute = DashboardWhatsappBotRouteImport.update({
  id: '/whatsapp-bot',
  path: '/whatsapp-bot',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardUserManagementRoute = DashboardUserManagementRouteImport.update({
  id: '/user-management',
  path: '/user-management',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardChatRoute = DashboardChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAiAgentRoute = DashboardAiAgentRouteImport.update({
  id: '/ai-agent',
  path: '/ai-agent',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardKnowledgeSourcesIndexRoute =
  DashboardKnowledgeSourcesIndexRouteImport.update({
    id: '/knowledge-sources/',
    path: '/knowledge-sources/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardKnowledgeSourcesFolderIdRoute =
  DashboardKnowledgeSourcesFolderIdRouteImport.update({
    id: '/knowledge-sources/$folderId',
    path: '/knowledge-sources/$folderId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/ai-agent': typeof DashboardAiAgentRoute
  '/dashboard/chat': typeof DashboardChatRoute
  '/dashboard/user-management': typeof DashboardUserManagementRoute
  '/dashboard/whatsapp-bot': typeof DashboardWhatsappBotRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/knowledge-sources/$folderId': typeof DashboardKnowledgeSourcesFolderIdRoute
  '/dashboard/knowledge-sources': typeof DashboardKnowledgeSourcesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/ai-agent': typeof DashboardAiAgentRoute
  '/dashboard/chat': typeof DashboardChatRoute
  '/dashboard/user-management': typeof DashboardUserManagementRoute
  '/dashboard/whatsapp-bot': typeof DashboardWhatsappBotRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/knowledge-sources/$folderId': typeof DashboardKnowledgeSourcesFolderIdRoute
  '/dashboard/knowledge-sources': typeof DashboardKnowledgeSourcesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/ai-agent': typeof DashboardAiAgentRoute
  '/dashboard/chat': typeof DashboardChatRoute
  '/dashboard/user-management': typeof DashboardUserManagementRoute
  '/dashboard/whatsapp-bot': typeof DashboardWhatsappBotRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/knowledge-sources/$folderId': typeof DashboardKnowledgeSourcesFolderIdRoute
  '/dashboard/knowledge-sources/': typeof DashboardKnowledgeSourcesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/dashboard/ai-agent'
    | '/dashboard/chat'
    | '/dashboard/user-management'
    | '/dashboard/whatsapp-bot'
    | '/dashboard/'
    | '/dashboard/knowledge-sources/$folderId'
    | '/dashboard/knowledge-sources'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard/ai-agent'
    | '/dashboard/chat'
    | '/dashboard/user-management'
    | '/dashboard/whatsapp-bot'
    | '/dashboard'
    | '/dashboard/knowledge-sources/$folderId'
    | '/dashboard/knowledge-sources'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/dashboard/ai-agent'
    | '/dashboard/chat'
    | '/dashboard/user-management'
    | '/dashboard/whatsapp-bot'
    | '/dashboard/'
    | '/dashboard/knowledge-sources/$folderId'
    | '/dashboard/knowledge-sources/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/whatsapp-bot': {
      id: '/dashboard/whatsapp-bot'
      path: '/whatsapp-bot'
      fullPath: '/dashboard/whatsapp-bot'
      preLoaderRoute: typeof DashboardWhatsappBotRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/user-management': {
      id: '/dashboard/user-management'
      path: '/user-management'
      fullPath: '/dashboard/user-management'
      preLoaderRoute: typeof DashboardUserManagementRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/chat': {
      id: '/dashboard/chat'
      path: '/chat'
      fullPath: '/dashboard/chat'
      preLoaderRoute: typeof DashboardChatRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/ai-agent': {
      id: '/dashboard/ai-agent'
      path: '/ai-agent'
      fullPath: '/dashboard/ai-agent'
      preLoaderRoute: typeof DashboardAiAgentRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/knowledge-sources/': {
      id: '/dashboard/knowledge-sources/'
      path: '/knowledge-sources'
      fullPath: '/dashboard/knowledge-sources'
      preLoaderRoute: typeof DashboardKnowledgeSourcesIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/knowledge-sources/$folderId': {
      id: '/dashboard/knowledge-sources/$folderId'
      path: '/knowledge-sources/$folderId'
      fullPath: '/dashboard/knowledge-sources/$folderId'
      preLoaderRoute: typeof DashboardKnowledgeSourcesFolderIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardAiAgentRoute: typeof DashboardAiAgentRoute
  DashboardChatRoute: typeof DashboardChatRoute
  DashboardUserManagementRoute: typeof DashboardUserManagementRoute
  DashboardWhatsappBotRoute: typeof DashboardWhatsappBotRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardKnowledgeSourcesFolderIdRoute: typeof DashboardKnowledgeSourcesFolderIdRoute
  DashboardKnowledgeSourcesIndexRoute: typeof DashboardKnowledgeSourcesIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAiAgentRoute: DashboardAiAgentRoute,
  DashboardChatRoute: DashboardChatRoute,
  DashboardUserManagementRoute: DashboardUserManagementRoute,
  DashboardWhatsappBotRoute: DashboardWhatsappBotRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardKnowledgeSourcesFolderIdRoute:
    DashboardKnowledgeSourcesFolderIdRoute,
  DashboardKnowledgeSourcesIndexRoute: DashboardKnowledgeSourcesIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
